### ISSUE TITLE
rocprof  -i input.txt cannot work well

### ISSUE THREAD

**Issue by code-fool** [ROCm/rocprofiler#101]
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/44488158/205975372-f87a0dbb-2aff-44e7-89b8-65dba888c332.png">
 i can not get the result like this picture say
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/44488158/205976032-24184a3e-5da1-49f5-b696-a8a169fdbd02.png">

**Comment by harkgill-amd** [comment]
Hi @code-fool, I was not able to reproduce the issue you are seeing with the latest release of rocprof in ROCm 6.2. The parameters used in my test were the following.

1. input.txt 

```
# Perf counters group 1
pmc: MemUnitStalled,TCC_MISS[0]
# Filter by dispatches range, GPU index and kernel names
# supported range formats: "3:9", "3:", "3"
range: 0:1
gpu: 0
kernel: matrixTranspose
```
2. [MatrixTranspose ](https://github.com/ROCm/hip-tests/blob/develop/samples/2_Cookbook/0_MatrixTranspose/MatrixTranspose.cpp) sample from hip-tests.
3. MI100 paired with ROCm 6.2/rocprofiler 2.0.60200.60200-66

I then compiled and ran the MatrixTranpose sample with profiling using `rocprof -i input.txt ./MatrixTranspose`. After completion, `input.csv` resulted in the following:
```
Index,KernelName,gpu-id,queue-id,queue-index,pid,tid,grd,wgr,lds,scr,arch_vgpr,accum_vgpr,sgpr,wave_size,sig,obj,MemUnitStalled,TCC_MISS[0]
0,"matrixTranspose(float*, float*, int) [clone .kd]",2,0,1,1231427,1231427,1048576,16,0,0,8,8,16,64,0x0,0x705afa684880,0.0000000000,0
```
I will close out this ticket. If you are still encountering this issue after following the steps above, please comment your findings and I will re-open this ticket. Thanks!
