### ISSUE TITLE
rocProfiler install problem : where is the file rocprofiler.h ?

### ISSUE THREAD

**Issue by 6lonelyrainbow** [ROCm/rocprofiler#102]
To use the rocProfiler API you need the API header and to link your application with roctracer .so librray:

the API header: /opt/rocm/rocprofiler/include/rocprofiler.h
the .so library: /opt/rocm/lib/librocprofiler64.so

**Comment by harkgill-amd** [comment]
Hi @6lonelyrainbow, the API header and dynamic libraries can be found at
```
API header: /opt/rocm-{version}/include/rocprofiler/rocprofiler.h
Dynamic library (.so): /opt/rocm-{version}/lib/librocprofiler64.so
```
For example, with ROCm 6.2.0 and rocprofv1, the paths would be the following
```
API header: /opt/rocm-6.2.0/include/rocprofiler/rocprofiler.h 
Dynamic library (.so): /opt/rocm-6.2.0/lib/librocprofiler64.so
```
For more information on how to implement the API, please visit the documentation [here](https://rocm.docs.amd.com/projects/rocprofiler/en/latest/rocprofiler_spec.html).
