### ISSUE TITLE
Missing `#include <cstdint>` with GCC 13

### ISSUE THREAD

**Issue by tpkessler** [ROCm/rocprofiler#111]
Hi! I'm packaging ROCm for Arch Linux. With GCC 13, `cstdint` must be included to use types like `uint8_t`.

**Comment by harkgill-amd** [comment]
Closing issue as issue was resolved in commit https://github.com/ROCm/rocprofiler/commit/aac324cc0c5a80ad15cb2a1c3ee1f363eb86e155.
