### ISSUE TITLE
How to view the activity of the matrix core while the kernel is running？

### ISSUE THREAD

**Issue by deltaguo** [ROCm/rocprofiler#117]
I read the documentation about hardware counters and found that there is no introduction on how to monitor the active status of the matrix core. Is there currently a way to achieve this?

**Comment by ppanchad-amd** [comment]
@deltaguo Apologies for the lack of response.  Do you still need assistance with this ticket? Thanks!

**Comment by deltaguo** [comment]
@ppanchad-amd of course, i am still curious about this.

**Comment by ppanchad-amd** [comment]
Hi @deltaguo, Internal ticket has been created to assist with your issue. Thanks!

**Comment by schung-amd** [comment]
Hi @deltaguo, sorry for the delay, I've been reaching out to internal teams to see if we have specific guidance on this. In theory I think this should be possible with Analysis View (https://rocmdocs.amd.com/projects/rocprofiler/en/latest/how-to/rocprofv2-usage.html#analysis-view), which can be used to profile your code at the instruction level, but I haven't personally tested this. Looking at the MFMA and WMMA instructions should provide insight on when and how the matrix core is being used.

**Comment by schung-amd** [comment]
Closing this for now, if you have more specific questions or want additional guidance feel free to comment and we can reopen this.
