### ISSUE TITLE
missing hip_ostream_ops.h and unable to find library -lrocm_smi64

### ISSUE THREAD

**Issue by Cydia2018** [ROCm/rocprofiler#118]
In file included from /workspace/rocprofiler/src/core/session/tracer/src/roctracer.h:24,
from /workspace/rocprofiler/src/core/hsa/hsa_support.h:106,
from /workspace/rocprofiler/src/core/rocprofiler.cpp:42:
/opt/rocm/include/hip/hip_runtime.h:66:2: error: #error ("Must define exactly one of HIP_PLATFORM_AMD or HIP_PLATFORM_NVIDIA");
66 | #error("Must define exactly one of HIP_PLATFORM_AMD or HIP_PLATFORM_NVIDIA");
| ^~~~~
In file included from /opt/rocm/include/hip/hip_runtime.h:113,
from /workspace/rocprofiler/src/core/session/tracer/src/roctracer.h:24,
from /workspace/rocprofiler/src/core/hsa/hsa_support.h:106,
from /workspace/rocprofiler/src/core/rocprofiler.cpp:42:
/opt/rocm/include/hip/hip_runtime_api.h:6926:2: error: #error ("Must define exactly one of HIP_PLATFORM_AMD or HIP_PLATFORM_NVIDIA");
6926 | #error("Must define exactly one of HIP_PLATFORM_AMD or HIP_PLATFORM_NVIDIA");
| ^~~~~
In file included from /opt/rocm/include/hip/hip_runtime.h:114,
from /workspace/rocprofiler/src/core/session/tracer/src/roctracer.h:24,
from /workspace/rocprofiler/src/core/hsa/hsa_support.h:106,
from /workspace/rocprofiler/src/core/rocprofiler.cpp:42:
/opt/rocm/include/hip/library_types.h:48:2: error: #error ("Must define exactly one of HIP_PLATFORM_AMD or HIP_PLATFORM_NVIDIA");
48 | #error("Must define exactly one of HIP_PLATFORM_AMD or HIP_PLATFORM_NVIDIA");
| ^~~~~
In file included from /opt/rocm/include/hip/hip_runtime.h:116,
from /workspace/rocprofiler/src/core/session/tracer/src/roctracer.h:24,
from /workspace/rocprofiler/src/core/hsa/hsa_support.h:106,
from /workspace/rocprofiler/src/core/rocprofiler.cpp:42:
/opt/rocm/include/hip/hip_vector_types.h:38:2: error: #error ("Must define exactly one of HIP_PLATFORM_AMD or HIP_PLATFORM_NVIDIA");
38 | #error("Must define exactly one of HIP_PLATFORM_AMD or HIP_PLATFORM_NVIDIA");
| ^~~~~
In file included from /workspace/rocprofiler/src/core/hsa/hsa_support.h:106,
from /workspace/rocprofiler/src/core/rocprofiler.cpp:42:
/workspace/rocprofiler/src/core/session/tracer/src/roctracer.h:33:10: fatal error: hip_ostream_ops.h: No such file or directory
33 | #include "hip_ostream_ops.h"
| ^~~~~~~~~~~~~~~~~~~
compilation terminated.

--------------------------------------------------

[ 40%] Linking HIP executable pcie_bw_test
ld.lld: error: unable to find library -lrocm_smi64
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tests/microbenchmarks/CMakeFiles/pcie_bw_test.dir/build.make:91: tests/microbenchmarks/pcie_bw_test] Error 1
make[2]: Leaving directory '/workspace/rocprofiler/build'
make[1]: *** [CMakeFiles/Makefile2:1587: tests/microbenchmarks/CMakeFiles/pcie_bw_test.dir/all] Error 2

I have `pip install Cppheaderparser`, but still encountered above problem in build process.

**Comment by jrmadsen** [comment]
It looks like build is failing because of an error building a benchmark test which isn’t necessary for installation so just comment out this line here:

 https://github.com/ROCm-Developer-Tools/rocprofiler/blob/4f779d11d5cb1475f68c3055497c6902b2d8b393/tests/CMakeLists.txt#L9

**Comment by jrmadsen** [comment]
My apologizes, the comment above is just with respect to the second error. With regard to the first, what version of ROCm do you have installed in `/opt/rocm`? You can usually easily determine this with `realpath /opt/rocm` and you will see something like `/opt/rocm-X.Y.Z` where `X.Y.Z` is the version number

**Comment by Cydia2018** [comment]
> My apologizes, the comment above is just with respect to the second error. With regard to the first, what version of ROCm do you have installed in `/opt/rocm`? You can usually easily determine this with `realpath /opt/rocm` and you will see something like `/opt/rocm-X.Y.Z` where `X.Y.Z` is the version number

Thanks for your suggestion, but the first error still exists, the rocm I installed is 5.4.0

**Comment by jrmadsen** [comment]
Have you checked out the `rocm-5.4.x` branch?

**Comment by Cydia2018** [comment]
> Have you checked out the `rocm-5.4.x` branch?

thanks, i build it successfully.
