### ISSUE TITLE
Question about configuration "range"

### ISSUE THREAD

**Issue by gty111** [ROCm/rocprofiler#120]
`rocprof` needs a input file and `range` can be configured in the input file. But what exactly does `range` mean? Is there any explanation about it?

**Comment by harkgill-amd** [comment]
Hi @gty111, the following excerpt is from the [rocprofiler 2.0.0 documentation](https://rocm.docs.amd.com/projects/rocprofiler/en/latest/index.html). 

Range: The row beginning with the keyword range: specifies the range of kernel dispatches. Specifying range is helpful in cases where the application causes multiple kernel dispatches and users want to filter some kernel dispatches. In the above example, the range: 0:1 depicts that one kernel is profiled.

You can find more information on the parameters of the input file [here](https://rocm.docs.amd.com/projects/rocprofiler/en/latest/how-to/rocprofv2-usage.html#input-file).
