### ISSUE TITLE
Can we use rocprofiler_open() concurrently? 

### ISSUE THREAD

**Issue by hgtsoi** [ROCm/rocprofiler#121]
I found "concurrent" not yet supported in rocm5.5.
But I am wondering if we can use rocprofiler_open() api concurrently?

**Comment by ppanchad-amd** [comment]
@hgtsoi Apologies for the lack of response. Do you still need assistance with this ticket? If not, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@hgtsoi Closing ticket.  Please let us know if you still need assistance and we will re-open the ticket. Thanks!
