### ISSUE TITLE
Please add gfx1100 support for aqlprofie

### ISSUE THREAD

**Issue by xuwd1** [ROCm/rocprofiler#125]
Currently when trying to profile counter metrics for gfx1100 both rocprof and rocprofv2 consistently report "GFXIP is not supported(gfx1100)". By investigating the source code and the ROCm documents as far as I could tell this problems roots from the proprietary aql profiler library not supporting gfx1100 devices (it seems like the whole gfx11 series are completely unsupported). Both 5.5.3 and 5.6.0 versions of the library were tested but neither works.
Honestly, with full respect, I don't understand why this is the case considering the fact that Radeon Pro W7900/7800 has released 3-4 months ago and the `gpu_performance_api` has supported hw counters reading on gfx1100 and gfx1103. Please consider updating the `aqlprofile` library to support these new devices!

**Comment by ApoKalipse-V** [comment]
GFX11 support was added in ROCm 5.7.0
