### ISSUE TITLE
/opt/rocm/libexec/rocprofiler/tblextr.py: ROCTX range begin not found, pid()

### ISSUE THREAD

**Issue by rommelDB** [ROCm/rocprofiler#126]
I have a Fortran90 app, and I got this error when trying to get the profiling report with:
```
rocprof --hip-trace --roctx-trace ./foo
```

My main.F90 code is like:
```
...
use roctx, only: roctxRangePushA, roctxRangePop
use ISO_C_BINDING, only: C_NULL_CHAR

subroutine foo(...)
  ret = roctxRangePushA("foo"//C_NULL_CHAR)
  ... more code ...
  call roctxRangePop()
end subroutine foo
...
```

And the roctx module is the same than:
https://github.com/cp2k/dbcsr/blob/HEAD/src/acc/hip/dbcsr_hip_profiling.F

Also, the building useful line is:
```
LDFLAGS=-L$(ROCM_PATH)/lib -lroctx64
```

It seems it should work. But, probably, I'm doing something wrong, btw rocm version is 5.2.3.

**Comment by ppanchad-amd** [comment]
@rommelDB Apologies for the lack of response. Can you please check if your issue still exists with the latest ROCm 6.2? If resolved, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@rommelDB Closing this ticket. Please let us know if you still encounter the issue with the latest ROCm and we will further investigate the issue. Thanks!
