### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by MatPoliquin** [ROCm/rocprofiler#13]
Is there plans to make a GUI similar to Nvidia Visual Profiler?

**Comment by MathiasMagnus** [comment]
There is CodeXL which uses the same library to obtain perf counters which rocprof does. Does that suit your needs?

**Comment by MatPoliquin** [comment]
I haven't been able to make CodeXL work with latest ROCm, is there is an up to date tutorial I can follow?

**Comment by MathiasMagnus** [comment]
I have absolutely no idea, as I'm using CodeXL on Windows and it works well with Radeon Software. No ROCm here.

**Comment by Dantali0n** [comment]
> I have absolutely no idea, as I'm using CodeXL on Windows and it works well with Radeon Software. No ROCm here.

CodeXL can't capture OpenCL traces so for most compute applications it is useless. It is also superseded officially [uprof](https://developer.amd.com/amd-uprof/) which I have yet to try. In addition there is the [Radeon GPU Profiler (RGP)](https://radeon-gpuprofiler.readthedocs.io/en/latest/) which can collect OpenCL traces but only on specific cards.

The most common method using ROCm is by using the roc-profiler and opening the json traces into chrome::/tracing.

It is pretty hard to find any of this information as in typical AMD fashion every link or article on the old tools has been blasted into oblivion with all the old url's now going straight back to the homepage...

**Comment by eshcherb** [comment]
Currently profiler supports JSON format compatible with Google Chrome-tracing.

**Comment by EvgeniyPeshkov** [comment]
Hello @MatPoliquin! I would like to suggest [CLtracer](https://www.cltracer.com/). It's an OpenCL profiler with modern and easy-to-use UI. CLtracer supports any GPU and available on Windows and Linux.

**Comment by ppanchad-amd** [comment]
@MatPoliquin Closing ticket. Please re-open if you still need assistance with this ticket. Thanks!
