### ISSUE TITLE
[Feature]: add cmake imported target

### ISSUE THREAD

**Issue by maartenarnst** [ROCm/rocprofiler#137]
### Suggestion Description

Unless I make a mistake, it appears the roc profiler installation currently does not create the cmake logic that users can use in downstream code to help cmake find the roc profiler and set targets accordingly. In particular, it appears the roc profiler installation is missing either a cmake config file or a find module. This feature suggestion is thus to provide such cmake logic. 

Also tagging @jrmadsen because such a find module file is available in omnitrace. Perhaps it could be incorporated here?

- https://github.com/AMDResearch/omnitrace/tree/main/cmake/Modules

**Comment by sohaibnd** [comment]
Hi @maartenarnst, sorry for the delay. If you want to use rocprofiler as a dependency downstream, you can copy the [Findrocprofiler.cmake](https://github.com/ROCm/omnitrace/blob/main/cmake/Modules/Findrocprofiler.cmake) file from the omniperf repo to your project (e.g. in `<your project root>/cmake/Modules`) and add the file's location to `CMAKE_MODULE_PATH` so you can call `find_package(rocprofiler)` (see [tutorial](https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/How-To-Find-Libraries#how-package-finding-works) and [this post](https://stackoverflow.com/questions/37558571/add-include-a-cmake-that-finds-a-package-into-cmake)).

Note that CMake find modules for a project are not usually part of the project itself.

**Comment by sohaibnd** [comment]
@maartenarnst I'm going to close this issue due to inactivity. If you have issues using the Findrocprofiler.cmake file from in your project to find rocprofiler, feel free to re-open this issue.
