### ISSUE TITLE
[Feature]:  Ignore unsupported architectures

### ISSUE THREAD

**Issue by benrichard-amd** [ROCm/rocprofiler#138]
### Suggestion Description

My laptop is an HP Omen. It has a gfx90c (not supported) and a gfx1032 (supported). The gfx90c cannot be disabled, even in the BIOS. I cannot run rocprof because it detects the gfx90c then fails:

```
terminate called after throwing an instance of 'rocprofiler::util::exception'
  what():  Translate(), ImportMetrics: bad block name 'GRBM', GFXIP is not supported(gfx90c)
/usr/local/bin/rocprofv2: line 304:  4006 Aborted                 (core dumped) LD_PRELOAD=$LD_PRELOAD:$ROCM_DIR/lib/rocprofiler/librocprofiler_tool.so $*
```

Shouldn't we be ignoring unsupported GPUs and only failing if a supported one cannot be detected?

**Comment by oldxie** [comment]
any update ?
rocminfo show that 2 devices (gfx1030 gfx90c) and I try to set ROCR_VISIBLE_DEVICES only gfx1030 but doesn't work


`export ROCR_VISIBLE_DEVICES="1,GPU-****" && sudo rocprofv2 --list-counters
terminate called after throwing an instance of 'rocprofiler::util::exception'
  what():  Translate(), ImportMetrics: bad block name 'GRBM', GFXIP is not supported(gfx90c)
/usr/bin/rocprofv2: line 87: 828160 Aborted                 (core dumped) /opt/rocm-6.1.1/libexec/rocprofiler/ctrl`

**Comment by benrichard-amd** [comment]
Re-tested on ROCm 6.3.0-39. Can no longer reproduce.
