### ISSUE TITLE
Host to Device transfer

### ISSUE THREAD

**Issue by MatPoliquin** [ROCm/rocprofiler#14]
Is there a way to profile Host to Device transfers like for nvidia profiler?

**Comment by nwolfey21** [comment]
@MatPoliquin, as of ROCm 3.0, run: `$ /opt/rocm/bin/rocprof --hsa-trace <appWithArguments>`
The result will be a `results.json` file in your working directory that you can load in chrome://tracing in your chrome browser. The .json trace will display copies, HSA signals and kernel calls. Additionally, a `results_mcopy.csv` file will be generated in your working directory with the specifics of the transfers.

**Comment by eshcherb** [comment]
@MatPoliquin, could you close the ticket?
