### ISSUE TITLE
[Issue]: rocprofv2 --hip-trace --roctx-trace  --plugin perfetto, no ROCTX in Perfetto UI viewer 

### ISSUE THREAD

**Issue by hgtsoi** [ROCm/rocprofiler#142]
### Problem Description

rocprofv2 rocprofv2 --hip-trace --roctx-trace  --plugin perfetto, no ROCTX in Perfetto UI viewer 

but --plugin file as by default, it can put ROCTX marker in logs.

rocprof has roctx range in chrome trace json. can we get roctx in perfetto format?

### Operating System

Ubuntu 22.04  rocm-5.7.1

### CPU

AMD

### GPU

AMD Instinct MI100

### ROCm Version

ROCm 5.7.1

### ROCm Component

rocprofiler

### Steps to Reproduce

any case with ROCTX marker can reproduce this issue.

**Comment by ppanchad-amd** [comment]
Hi @hgtsoi, internal ticket has been created to investigate this issue. Thanks!

**Comment by schung-amd** [comment]
Hi @hgtsoi, thanks for bringing this to our attention. This has been addressed (https://github.com/ROCm/rocprofiler/commit/a6c31edfc3085b6e258b75e450cade35dedba5c8) and rocprofv2 should now output the ROCTX marks in addition to the ROCTX ranges when using the Perfetto plugin. Feel free to reopen this issue if this does not resolve your problem.
