### ISSUE TITLE
How to use rocprofv2 to obtain the metrics supported by the current device.

### ISSUE THREAD

**Issue by hi20240217** [ROCm/rocprofiler#146]
How to use rocprofv2 to obtain the metrics supported by the current device.

**Comment by ppanchad-amd** [comment]
Hi @hi20240217, internal ticket has been created to assist with your question. Thanks!

**Comment by darren-amd** [comment]
Hi @hi20240217,

To obtain the metrics for the current device, try running:
`rocprofv2 --list-counters`

The following is a sample output from the --list-counters option. The output has been truncated for explanation:
```
gfx1030:0 : SQ_WAVES
: Count number of waves sent to SQs. {emulated, global, C1}
block SQ can only handle 8 counters at a time
```

The fields in the output are:

gfx1030:0 - The GPU architecture and GPU ID (separated by colon). The GPU ID needs to be specified as there might be multiple GPUs in the system.

SQ_WAVES - The counter name. Typically, the first token before the first underscore is the GPU block name. Here, SQ is the block that is responsible for managing wavefronts and issuing instructions.

Here is some further documentation where you can also find more information: [rocprofv2 Documentation](https://rocm.docs.amd.com/projects/rocprofiler/en/latest/how-to/rocprofv2-usage.html#kernel-profiling). Hopefully that answers your question, thanks!
