### ISSUE TITLE
Clearify build instructions

### ISSUE THREAD

**Issue by tpkessler** [ROCm/rocprofiler#18]
I'm trying to build `rocprofiler` under Arch Linux from source. The build instructions in the README state
```
- ROCm is required.
```
Could you please specify which parts of ROCm are needed? I'm confused since `rocprofiler` itself is part of ROCM: https://github.com/RadeonOpenCompute/ROCm#rocm-binary-package-structure

**Comment by eshcherb** [comment]
I have updated th README as:
 - ROCm is required.
  ROCr-runtime and roctracer are needed

https://github.com/ROCm-Developer-Tools/rocprofiler#to-build-with-the-current-installed-rocm

**Comment by tpkessler** [comment]
Thank you @eshcherb. This matches the dependencies I found by looking into the `CMakeLists.txt` and trial and error.
