### ISSUE TITLE
rocprof not running the executable

### ISSUE THREAD

**Issue by ye-luo** [ROCm/rocprofiler#19]
I noticed that rocprof completely bypasses running the executable.
```
$ OMP_NUM_THREADS=8 rocprof --hsa-trace --obj-tracking on ./bin/check_spo_batched 
RPL: on '200317_135650' from '/opt/rocm-3.1.0/rocprofiler' in '/home/yeluo/opt/miniqmc/build_ryzen_aomp_MP'
RPL: profiling '"./bin/check_spo_batched"'
RPL: input file ''
RPL: output dir '/tmp/rpl_data_200317_135650_31629'
RPL: result dir '/tmp/rpl_data_200317_135650_31629/input_results_200317_135650'
ROCProfiler: input from "/tmp/rpl_data_200317_135650_31629/input.xml"
  0 metrics
  0 traces
ROCTracer (pid=31651): 
    HSA-trace()
    HSA-activity-trace()
File '/home/yeluo/opt/miniqmc/build_ryzen_aomp_MP/results.hsa_stats.csv' is generating

File '/home/yeluo/opt/miniqmc/build_ryzen_aomp_MP/results.json' is generating

File '/home/yeluo/opt/miniqmc/build_ryzen_aomp_MP/results.json' is generating
```
Any idea what is wrong?

**Comment by ekuznetsov139** [comment]
Try to run it again after 
`sudo apt-get install --reinstall hsa-amd-aqlprofile`

**Comment by pfotouhi** [comment]
I've been dealing with a similar issue, and re-installing hsa-amd-aqlprofile solved it.
Moreover, I suggest double checking rocprof installation and making sure that tests (run.sh in your build directory) are successfully completed (at least for me it was a combination of both issues).

**Comment by ye-luo** [comment]
Re-installing hsa-amd-aqlprofile solved my issue.

**Comment by ye-luo** [comment]
Today I updated rocm to 3.3 and then I have to reinstall hsa-amd-aqlprofile again. The packaging team needs to sort out a better solution.
