### ISSUE TITLE
SQTT trace in rocprofiler 3.3

### ISSUE THREAD

**Issue by hgtsoi** [ROCm/rocprofiler#22]
I used to dump SQTT trace data with rocprofiler 2.1 and ROCm2.x but failed to get SQTT trace with latest build. How can I configure SQTT trace in rocprofiler 3.3? It errors out not recognizing the trace token SQTT.

my old xml configuration: 
```xml
<trace name="SQTT">
</trace>
```

Could you please help with this?

**Comment by eshcherb** [comment]
It is not supported
