### ISSUE TITLE
rocprof --hip-trace not working properly.

### ISSUE THREAD

**Issue by SaurabhKavi** [ROCm/rocprofiler#23]
HI.
I am trying to profile one of my test cases using the rocprof --hip-trace, but i am getting "_wrap_buffer(), worker thread is not started_ ". As soon as this message is coming, rocprof is closing without capturing any details. If I am using rocprof without --hip-trace I am not facing this issue. Can someone please point out what i need to do to resolve this.
I am using rocm-3.3 and gfx-906.

Thanks.
Saurabh

**Comment by eshcherb** [comment]
Could you update ROCM till 3.5?

**Comment by SarbojitAMD** [comment]
I am using the latest rocm stack but I can't see hip traces in result.json. The command that I am using is "/opt/rocm/bin/rocprof --stats --hip-trace --sys-trace --hsa-trace --kfd-trace --roctx-trace <app_binary>". Profiling finishes without any error but I can't see HIP API calls present in the trace. Only HSA calls can be seen.

Thanks

**Comment by zhaozhangjian** [comment]
Hi Sarbojit,
I came across the same problem as you did, and I am also using rocm-3.3.x and gfx-906. I built and installed HIP with USE_PROF_API macro defined to 1. Have you found the solution to this issue?
Looking forward to your reply!

Thanks

**Comment by zhaozhangjian** [comment]
Hi there,
I found that adding two definitions of **-DUSE_PROF_API=1 -DPROF_API_HEADER_DIR=/opt/rocm/roctracer/include/ext** when build both HIP and hcc components can solve this problem.
