### ISSUE TITLE
[3.3] failed to dump v3 code object

### ISSUE THREAD

**Issue by zjunweihit** [ROCm/rocprofiler#26]
When I use rocm 3.3 to dump TensorFlow data, it pops below error.
Does that mean it does not support V3 code object for now?
```
error(4096) "QueryKernelName(), Error: V3 code object detected - code objects tracking should be enabled
```

**Comment by gootsing** [comment]
You may add option "--obj-tracking on" to enable this feature.

**Comment by zjunweihit** [comment]
> You may add option "--obj-tracking on" to enable this feature.
Thanks for your reply.

I could continue with the object option. but the number of kernel increases a lot.
* without the option, 62 kernels are tracked with pmc data
* with the option, 76481 kernels are traced with pmc data

what's different in doing profiling when the option is enabled?
Thanks.

**Comment by eshcherb** [comment]
Hi zjunweihit, coudl you explain what do you mean under:
> without the option, 62 kernels are tracked with pmc data
> with the option, 76481 kernels are traced with pmc data

What option do you mean?
My understanding that without  "--obj-tracking on" option it is crashed, doesn't it?

**Comment by eshcherb** [comment]
"--obj-tracking on" will be enabled in 3,6 by default.
The option enabling V3 code object support.

**Comment by zjunweihit** [comment]
> 
> 
> Hi zjunweihit, coudl you explain what do you mean under:
> 
> > without the option, 62 kernels are tracked with pmc data
> > with the option, 76481 kernels are traced with pmc data
> 
> What option do you mean?
> My understanding that without "--obj-tracking on" option it is crashed, doesn't it?

I'm running a tensorflow app. When I use rocprofiler with `--obj-tracking on` to get PMC data, it could trace more kernels(76481) in the output file. otherwise, there are only 62 kernels tracked in the output file.
So I guess it not only enables v3 code object support, but also tracks more kernels.
Is that right?

**Comment by parepate** [comment]
@zjunweihit, when you don't use the option **_--obj-tracking on_** to get PMC data, at that time it got crashed while executing kernel with V3 code object. So no kernels dump after rocprof crash. But with the option **_--obj-tracking on_** your full Application running with rocprof without any issue so now you are able to capture more kernels.

**Comment by zjunweihit** [comment]
> 
> 
> @zjunweihit, when you don't use the option **_--obj-tracking on_** to get PMC data, at that time it got crashed while executing kernel with V3 code object. So no kernels dump after rocprof crash. But with the option **_--obj-tracking on_** your full Application running with rocprof without any issue so now you are able to capture more kernels.

Exactly.
Sorry I missed one thing to comment. I did some hack here to set invalid data.
If no **_--obj-tracking on_**, rocprofiler could not get the data there, so I set the value as **-1**, then the profiler could continue the work with invalid data.
In this case, I could run the profiler both with and without **_--obj-tracking on_**.
And the results are different. 
However, I think it a bit more, maybe some kernels didn't get tracked at all during profiling(even no invalid data then).
```
  166       ############ Junwei ########################                              
  167       #print ("--> each key: {}, {}".format(ind, entry))                        
  168       dispatch_number = entry['Index']                                          
  169       if ind != dispatch_number: fatal("Dispatch #" + ind + " index mismatch (" + dispatch_number + ")\n")
  170       #val_list = [entry[var] for var in var_list]                              
  171       ############ Junwei ########################                              
  172       val_list = []                                                             
  173       for var in var_list:                                                      
  174         if var in entry.keys():                                                 
  175           val_list.append(entry[var])                                           
  176         else:                                                                   
  177           val_list.append('-1')                                                 
  178       ############################################   
```
