### ISSUE TITLE
List Basic Command Error

### ISSUE THREAD

**Issue by ghost** [ROCm/rocprofiler#28]
When running rocprof --list-basic I get the following error. Any idea what the cause may be?

![image](https://user-images.githubusercontent.com/66755276/85887958-89ed4c00-b79d-11ea-949e-52dc995527cf.png)

**Comment by eshcherb** [comment]
Will be fixed in 3.6
For now just look the counters and metrics in XML config: 
/opt/rocm/rocprofiler/lib/metrics.xml
/opt/rocm/rocprofiler/lib/gfx_metrics.xml
