### ISSUE TITLE
question about profiling HIP and OpenMP programs

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm/rocprofiler#35]
May you please advise which commands should be used to profile HIP and OpenMP implementations of a program?   It is possible that users may put the timers at the wrong places in the HIP and OpenMP source files, so I would like to reply on the profiler for a fair comparison. 

Thanks for your instructions!

**Comment by ppanchad-amd** [comment]
@zjin-lcf Apologies for the lack of response. Do you still need assistance with this ticket? If not, please close the ticket. Thanks!
