### ISSUE TITLE
rocm-3.10 typos

### ISSUE THREAD

**Issue by ashterenli** [ROCm/rocprofiler#40]
RPL: on '210105_080245' from '/opt/rocm-3.10.0/rocprofiler'

rocprof -h

  --timestamp <on|off> - to turn on/off the kernel disoatches timestamps, dispatch/begin/end/complete [off]

change "disoatches" to "dispatches"

  --parallel-kernels - to enable cnocurrent kernels

change "cnocurrent" to "concurrent"

**Comment by ashterenli** [comment]
and here:

  --trace-period <dealy:length:rate> - to enable trace with initial delay, with periodic sample length and rate

change "dealy" to "delay"

**Comment by harkgill-amd** [comment]
Hi @ashterenli, sorry for the delay in response and thank you for pointing these typos out. Looks like the first two typos you mentioned have since been fixed but I still see `--trace-period dealy`. Will pass this along to the internal team.

**Comment by harkgill-amd** [comment]
All the typos mentioned in this issue and many more have been fixed. The latest commit, https://github.com/ROCm/rocprofiler/commit/1a63cba43d9cf71fda70f3dfb0472688475104a5, is in staging and the fixes will be present in ROCm 6.3. Thanks!
