### ISSUE TITLE
free(): corrupted unsorted chunks

### ISSUE THREAD

**Issue by yoann-heitz** [ROCm/rocprofiler#41]
When running the following command 
```
./rocprofiler/bin/rocprof --hsa-trace --hip-trace --kfd-trace -d traces python3 ./test.py
```
I sometimes get the following error 
```
free(): corrupted unsorted chunks
./rocprofiler/bin/rocprof: line 271: 861483 Aborted                 (core dumped) "python3" "./test.py"
```
I use rocm-4.0.0 and I cloned and built rocprofiler and roctracer from the github repositories. I used both amd-master and rocm-4.0.x branches and the error occurs in both cases. 

[unsorted_chunks_error.txt](https://github.com/ROCm-Developer-Tools/rocprofiler/files/6171122/unsorted_chunks_error.txt)
[test.py.zip](https://github.com/ROCm-Developer-Tools/rocprofiler/files/6171133/test.py.zip)

**Comment by harkgill-amd** [comment]
Hi @yoann-heitz, apologies for the lack of response once again. Looks like the test.py.zip folder linked is empty/broken. Are you still experiencing this issue as of ROCm 6.2.0?

**Comment by harkgill-amd** [comment]
Closing this issue out. @yoann-heitz, if you are still encountering this error with the latest ROCm 6.2.1 release, please leave a comment and I will re-open this ticket. Thanks!
