### ISSUE TITLE
Rocprofiler issue with AMD OpenMP (aomp)

### ISSUE THREAD

**Issue by arfio** [ROCm/rocprofiler#49]
Hi,
I tried getting tracing data of an OpenMP example program of AOMP (vmulsum) and I got a segmentation fault tracing either with hsa, kfd or hip.
I recorded a debug log using the following command:
`$ LD_DEBUG=libs rocprof --hsa-trace vmulsum 2&>1 > log.txt`
Here is the log.txt file:
[log.txt](https://github.com/ROCm-Developer-Tools/rocprofiler/files/6735885/log.txt)

I am using a gfx900, Ubuntu 20.04 with ROCm 4.2

**Comment by ye-luo** [comment]
@arfio Your log indicates missing libhsa-amd-aqlprofile64.so which is from hsa-amd-aqlprofile package.

Developers, please handle failure when loading dynamic library (dlopen?) instead of putting segmentation fault in front of users.

**Comment by ye-luo** [comment]
No more crash with ROCm 4.5.2 release

**Comment by arfio** [comment]
I tested again with ROCm 5.0.0 and do not have this issue.
