### ISSUE TITLE
Is there any update about the document?

### ISSUE THREAD

**Issue by adfc93** [ROCm/rocprofiler#52]
Hi, is there any update about the document? 
It seems that something has changed.
For example, in the document, it says
```
const char* rocprofiler_error_string();
```
but in fact, the function is
```
hsa_status_t rocprofiler_error_string(
    const char** str); 
```
Thank you.

**Comment by harkgill-amd** [comment]
Hi @adfc93, apologies for the lack of response. An internal ticket has been created to update and fix the documentation. Thanks!

**Comment by harkgill-amd** [comment]
@adfc93, thanks again for notifying us of the issue. https://github.com/ROCm/rocprofiler/commit/865e64753ac01fd26dcbe9d408ac6fdd43586991 has been merged into staging. The documentation will be updated for the ROCm 6.3 release.
