### ISSUE TITLE
Assumption about directory layout breaks Spack support.

### ISSUE THREAD

**Issue by vchuravy** [ROCm/rocprofiler#58]
https://github.com/ROCm-Developer-Tools/rocprofiler/blob/93778bdc4fa5403fedede3afcc1155338c62a6f3/bin/rpl_run.sh#L29

When rocprofiler is installed with spack https://github.com/spack/spack/blob/29d344e4c72aadb1672a2c8f36f9ff773b636ac4/var/spack/repos/builtin/packages/rocprofiler-dev/package.py

The assumption that all of the rocm packages are installed next to each other in a common root like

```
/opt/rom
  rocprofiler
  roctracer
```

Does not hold, since the names are versioned.

**Comment by harkgill-amd** [comment]
Hi @vchuravy, sorry for the lack of response. Are you still experiencing this issue with the latest release of ROCm and rocprofiler?

**Comment by ppanchad-amd** [comment]
@vchuravy Closing ticket due to lack of activity.  Please feel free to re-open ticket if you still see the issue with the latest ROCm. Thanks!
