### ISSUE TITLE
error while loading shared libraries: libhsa-runtime64.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by shana34** [ROCm/rocprofiler#62]

**Comment by shana34** [comment]
I follow the guide in README, and get this...which confuse me a lot

**Comment by vasslavich** [comment]
I have the same problem. Is there any workaround?

**Comment by kikimych** [comment]
You can try to set LD_LIBRARY_PATH to /opt/rocm/lib explicitly.
Which version of rocm are you using?

**Comment by kahmed10** [comment]
> You can try to set LD_LIBRARY_PATH to /opt/rocm/lib explicitly. Which version of rocm are you using?

I found libhsa-runtime64.so.1 under /opt/rocm/hsa/lib, and setting LD_LIBRARY_PATH to that location fixed the issue for me. I'm on ROCm 5.0.

**Comment by harkgill-amd** [comment]
Hi @shana34, apologies for the delay in response. Were you able to resolve your issue following @kikimych and @kahmed10's suggestions? You can also instruct the system linker on where to find .so files for ROCm by following the steps outlined at [Post-install instructions.](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/post-install.html#post-installation-instructions)

**Comment by harkgill-amd** [comment]
@shana34, I will close this ticket out for now. Please open a new ticket if you are experiencing similar errors with ROCm 6.2.1.
