### ISSUE TITLE
metrics table

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm/rocprofiler#65]
Nvidia and AMD GPUs are different, but a table shows the metrics in rocprofiler that correspond to the metrics in nvprof is helpful.  For example, could a user know the instructions per cycle using rocprofiler for a HIP program ?

https://docs.nvidia.com/cuda/profiler-users-guide/index.html#metrics-reference-7x

Thanks for your update.

**Comment by ppanchad-amd** [comment]
@zjin-lcf Apologies for the lack of response. Do you still need assistance with this ticket? If not, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@zjin-lcf Closing ticket. Please feel free to re-open the ticket if you still need assistance with this ticket. Thanks!
