### ISSUE TITLE
Missing symlinks in `<rocm-path>/lib`

### ISSUE THREAD

**Issue by bertwesarg** [ROCm/rocprofiler#68]
Why is there only the `.so` symlink in `<rocm-path>/lib` for rocprofiler? roctracer has `.so`, `.so.1`, and `.so.1.0.40500` symlinks. So have all other libs. This is ROCm 4.5.0.

**Comment by bertwesarg** [comment]
I see this on CentOS (yum) and Ubuntu (apt).

**Comment by harkgill-amd** [comment]
Hi @bertwesarg, as of ROCm 6.2.0, there are multiple shared object files under /opt/rocm/lib for rocprofiler such as 

```
librocprofiler64.so
librocprofiler64.so.1
librocprofiler64.so.1.0.60200
librocprofiler64.so.2
librocprofiler64.so.2.0.60200
librocprofiler64v2.so
```

I will close out this issue. If you feel your issue has not been addressed with the latest ROCm release, please open a new ticket. Thanks!
