### ISSUE TITLE
OpenCL support question

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm/rocprofiler#73]
When profiling an OpenCL program, the error message is:

ROCTracer (pid=1529322):
    HSA-trace()
    HIP-trace()
roctracer: Loading 'libamdhip64.so' failed, (null)

Am I doing right ? Thank you for your answer.

**Comment by kikimych** [comment]
You can try to set LD_LIBRARY_PATH

**Comment by zjin-lcf** [comment]
export LD_LIBRARY_PATH=/opt/rocm/lib:$LD_LIBRARY_PATH
rocprof --sys-trace ./exe
ROCTracer (pid=358571):
    HSA-trace()
    HIP-trace()
roctracer: Loading 'libamdhip64.so' failed, (null)

**Comment by guangzlu** [comment]
Have you solved it? I have add the route path of libamdhip64.so to LD_LIBRARY_PATH (for me is /opt/rocm-5.2.0/lib), I still face the problem. Can you tell me your way to solve it?

**Comment by kikimych** [comment]
https://github.com/ROCm-Developer-Tools/roctracer/blob/amd-master/src/core/loader.h#L56

Could you please build roctracer in debug, run `rocprofiler [profiler options] gdb 'program_name' ` set breakpoint on the line above and check actual path?

**Comment by gofreelee** [comment]
> Have you solved it? I have add the route path of libamdhip64.so to LD_LIBRARY_PATH (for me is /opt/rocm-5.2.0/lib), I still face the problem. Can you tell me your way to solve it?

hello, have you solved it ? i  am facing the same question
