### ISSUE TITLE
Timing Issues with MI50 and performance metrics

### ISSUE THREAD

**Issue by arfio** [ROCm/rocprofiler#83]
When tracing with the performance counters enabled on MI50, the kernel timings are not correct. When testing against MI100, the problem does not appear.

OS: Ubuntu 20.04
Kernel: 5.4.0-104
ROCm version: 5.0.0
GPU: tested on 2 configurations one with MI50 and one with MI100

**Comment by kikimych** [comment]
Could you please provide small synthetic test, build instructions and profiler options used to run?

**Comment by harkgill-amd** [comment]
Hi @arfio, if you are still experiencing this issue with the latest ROCm 6.2.0 release, please provide a minimal reproducible example which we can use to further investigate this issue. 

Please also note that support for MI50 is deprecated as of ROCm 6.2.0 meaning no new features will be added and support will be removed in a future ROCm release.

**Comment by harkgill-amd** [comment]
@arfio, if you are still encountering this issue, please provide a MRE and I will re-open this ticket. Thanks!
