### ISSUE TITLE
When activating tracing, one kernel event appears at a time before the program ran.

### ISSUE THREAD

**Issue by arfio** [ROCm/rocprofiler#84]
With ROCm 5.0.0 and MI50 or MI100, there is always a kernel event that appears at the beginning of the trace when activating performance counters and tracing.

OS: Ubuntu 20.04
Kernel: 5.4.0-104
ROCm version: 5.0.0
GPU: tested on 2 configurations one with MI50 and one with MI100

**Comment by ppanchad-amd** [comment]
@arfio Apologies for the lack of response. Can you please check if the issue still exists with the latest ROCm 6.2? If resolved, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@arfio Closing ticket. Please feel free to re-open the ticket if you still see the issue with the latest ROCm. Thanks!
