### ISSUE TITLE
rocprofiler accumulates results from previous runs with --stats option or without option

### ISSUE THREAD

**Issue by kikimych** [ROCm/rocprofiler#89]
way to reproduce:

`cat input.xml`
`<metric`
`  name=SQ_WAVES`
`></metric>`

`sudo rm /tmp/*.txt`

`cd /opt/rocm-4.5.2/hip/samples/2_Cookbook/0_MatrixTranspose`
`sudo make`
`sudo rocprof -i input.xml ./MatrixTranspose`

`cd /opt/rocm-4.5.2/hip/samples/2_Cookbook/13_occupancy`
`sudo make`
`sudo rocprof -i input.xml ./occupancy`

`cat input.csv`
Index,KernelName,gpu-id,queue-id,queue-index,pid,tid,grd,wgr,lds,scr,vgpr,sgpr,fbar,sig,obj,SQ_WAVES
0,"matrixTranspose(float*, float*, int) [clone .kd]",0,0,0,16313,16313,1048576,16,0,0,8,24,0,0x0,0x7fd140c0a6c0,31251
1,"multiply(float*, float*, float*, int) [clone .kd]",0,0,4,16425,16425,1000448,1024,0,0,8,24,0,0x0,0x7fd40ac0a800,15632

occupancy result contains runs from matrixTranspose test.
input.xml is copied to test directories

**Comment by ppanchad-amd** [comment]
@kikimych Can you please check if your issue still exists with the latest ROCm 6.2? If resolved, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@kikimych Closing ticket. Please re-open the ticket if you still see the issue with the latest ROCm and we will further investigate the issue. Thanks!
