### ISSUE TITLE
Typo in the help text

### ISSUE THREAD

**Issue by stvdwtt** [ROCm/rocprofiler#96]
Currently, the main help text for rocprof has a typo for the `--parallel-kernels` option:

`--parallel-kernels - to enable cnocurrent kernels`

which presumably should be:

`--parallel-kernels - to enable concurrent kernels`

**Comment by harkgill-amd** [comment]
Hi @stvdwtt, this was fixed with https://github.com/ROCm/rocprofiler/commit/c9efa4891e55c97759f778a592b5f971f605072b and is no longer seen in the latest ROCm release. Thanks!
